"""
Reads API keys from the current environment and writes them to .env.
Run once: python setup_env.py
"""

import os
import secrets
from pathlib import Path

ENV_PATH = Path(__file__).parent / ".env"

KEYS: list[tuple[str, str, str]] = [
    # (env_var, default_placeholder, comment)
    ("LITELLM_MASTER_KEY",    f"sk-gateway-{secrets.token_hex(8)}", "LiteLLM proxy master key (auto-generated)"),
    ("LITELLM_BASE_URL",      "http://localhost:4000",              "LiteLLM proxy URL"),
    # Core providers
    ("ANTHROPIC_API_KEY",     "sk-ant-REPLACE_ME",                  "Claude Pro (or pi-mono OAuth)"),
    ("GROQ_API_KEY",          "gsk_REPLACE_ME",                     "Groq Cloud (primary compaction engine)"),
    ("CEREBRAS_API_KEY",      "REPLACE_ME",                         "Cerebras (fast inference + backup compactor)"),
    ("GEMINI_API_KEY",        "REPLACE_ME",                         "Google Gemini 2.5 Pro / Flash"),
    # OpenAI / Codex
    ("OPENAI_CODEX_API_KEY",  "sk-REPLACE_ME",                      "Temporary Codex Plan (GPT-5.4)"),
    ("OPENAI_CODEX_BASE_URL", "https://api.openai.com/v1",          "Codex Plan base URL"),
    # GitHub Copilot
    ("GITHUB_COPILOT_TOKEN",  "ghp_REPLACE_ME",                     "GitHub Copilot / Cursor Pro (pi-mono OAuth)"),
    # OpenCode / MiniMax
    ("OPENCODE_API_KEY",      "REPLACE_ME",                         "OpenCode (pi-mono)"),
    ("OPENCODE_ZEN_API_KEY",  "REPLACE_ME",                         "OpenCode Zen / MiniMax m2.5"),
    ("OPENCODE_ZEN_BASE_URL", "https://api.minimaxi.chat/v1",       "MiniMax base URL"),
    # Gateways & secondary providers
    ("OPENROUTER_API_KEY",    "sk-or-v1-REPLACE_ME",                "OpenRouter universal gateway"),
    ("ZAI_API_KEY",           "REPLACE_ME",                         "ZAI / Zhipu AI"),
    ("KILO_API_KEY",          "REPLACE_ME",                         "Kilo AI"),
    ("BRAVE_API_KEY",         "REPLACE_ME",                         "Brave Search (web grounding)"),
    # Tuning
    ("COMPACTION_THRESHOLD",  "8",                                   "Compact after N non-system messages"),
    ("PRESERVE_TAIL",         "3",                                   "Keep last N messages verbatim"),
    ("LOG_LEVEL",             "INFO",                                "Logging verbosity"),
]


def build_env() -> str:
    lines = ["# Auto-generated by setup_env.py -- edit missing values manually\n"]
    found, missing = 0, 0

    for var, placeholder, comment in KEYS:
        value = os.environ.get(var, "")
        status = "+" if value else "-"
        lines.append(f"# {status} {comment}")
        if value:
            lines.append(f"{var}={value}")
            found += 1
        else:
            lines.append(f"{var}={placeholder}")
            missing += 1
        lines.append("")

    summary = f"# Populated: {found} | Needs manual entry: {missing}"
    lines.insert(1, summary + "\n")
    return "\n".join(lines)


def main() -> None:
    content = build_env()

    if ENV_PATH.exists():
        backup = ENV_PATH.with_suffix(".env.bak")
        backup.write_text(ENV_PATH.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"Backed up existing .env -> {backup.name}")

    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"Written: {ENV_PATH}\n")

    for var, _, comment in KEYS:
        value = os.environ.get(var, "")
        tag = "FOUND  " if value else "MISSING"
        print(f"  {tag}  {var}")


if __name__ == "__main__":
    main()
